spring.application.name=fitness-app-backend

# Configurazione Database H2 in memoria
spring.datasource.url=jdbc:h2:mem:ironfiredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostra le query SQL nel terminale (ottimo per imparare)
spring.jpa.show-sql=true
# Crea automaticamente le tabelle partendo dalle classi con @Entity
spring.jpa.hibernate.ddl-auto=create-drop

# Permette di accedere alla console web del database per vedere le tabelle
spring.h2.console.enabled=true


